### ISSUE TITLE
AppImage fails in systemd-less environment (Void Linux)

### ISSUE THREAD

**Issue by Kerrnel** [ente-io/ente#2552]
### Description

 $ ./ente-auth-v3.0.18-beta.2-x86_64.AppImage 
./ente_auth: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory

Note - after failure tried to xdev the .deb package - that installed but incorrectly (will report @ xdev)

### Version

3.0.18

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by ua741** [comment]
Currently, we don't any immedidate plan to support void linux and related distro.

**Comment by andbenn** [comment]
Ente is leaving a lot of good distros out in the cold.

Gentoo, Devuan, Antix, MX, Artix, Void, Alpine, Slackware and probably a few others.  Some of those distros are specifically targeted at old hardware and saving landfill space.

**Comment by ua741** [comment]
@Kerrnel Can you share the error from the latest image.

**Comment by Kerrnel** [comment]
AppImage 4.4.22 fails on an up-to-date Void due to libffi.so.7 installed by OS and AppImage searching for libffi.so.8

_I have been using enteauth on Void/KDE, installed via xdebinstall no problem. (Except for black display on auto launch when I reboot, but easy to restart it in that rare case)._

**Comment by ua741** [comment]
> AppImage 4.4.22 fails on an up-to-date Void due to libffi.so.7 installed by OS and AppImage searching for libffi.so.8
> 
> _I have been using enteauth on Void/KDE, installed via xdebinstall no problem. (Except for black display on auto launch when I reboot, but easy to restart it in that rare case)._


https://github.com/ente-io/ente/releases/tag/auth-v4.4.23 can you share the exact error for this version.

**Comment by Kerrnel** [comment]
**./ente-auth-v4.4.23-x86_64.AppImage**

/tmp/.mount_ente-aAgDJdA/enteauth: /lib64/libcurl.so.4: no version information available (required by /tmp/.mount_ente-aAgDJdA/lib/libsentry.so)

**ll /lib64/libcurl.***
-rw-r--r-- 1 root root 2003554 May  2 17:46 /lib64/libcurl.a
lrwxrwxrwx 1 root root      16 May  2 17:46 /lib64/libcurl.so -> libcurl.so.4.8.0*
lrwxrwxrwx 1 root root      16 May  2 17:46 /lib64/libcurl.so.4 -> libcurl.so.4.8.0*
-rwxr-xr-x 1 root root  988488 May  2 17:46 /lib64/libcurl.so.4.8.0*

Investigating... because I see it is also in the AppImage
Find: *curl*
./usr/lib/libcurl.so.4
./data/flutter_assets/assets/simple-icons/icons/curl.svg

Interesting in AppRun 

11 if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
12     export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOST_LIBRARY_PATH:$BUNDLED_LIBRARY_PATH"
13 else
14     export LD_LIBRARY_PATH="$BUNDLED_LIBRARY_PATH:$HOST_LIBRARY_PATH"
15 fi

When I flip line 14 as shown, back to libffi.so.8 issue.
If I copy libffi.so.8 from an ubuntu machine into ./usr/lib/ error goes away

**Comment by ua741** [comment]
The potential fix is available in the [nightly build](https://github.com/ente-io/nightly/releases/tag/auth-v4.4.24-beta) cc @Kerrnel

**Comment by Kerrnel** [comment]
Both 4.4.23 and 4.4.24 AppImage run fine on Void (and probably others).

I apologize for the prior noted failure which occured because I had the deb installed app running  which apparently resulted in the AppImage just silently stopping after the message. After terminating the deb-installed enteauth, I tested both -23 and -24.

This error noted before still shows:

```
./ente-auth-v4.4.24-beta-x86_64.AppImage 
/tmp/.mount_ente-afollbL/enteauth: /lib64/libcurl.so.4: no version information available (required by /tmp/.mount_ente-afollbL/lib/libsentry.so)
```

But they continue with the warnings below ... and ultimately function fine.

```
* (io.ente.auth:14780): CRITICAL **: 23:25:50.612: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (io.ente.auth:14780): CRITICAL **: 23:25:50.627: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (io.ente.auth:14780): CRITICAL **: 23:25:50.628: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (io.ente.auth:14780): CRITICAL **: 23:25:50.629: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (io.ente.auth:14780): CRITICAL **: 23:25:50.630: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
Gdk-Message: 23:25:50.631: Unable to load  from the cursor theme
 [ente_logging][INFO] [2026-06-12 23:25:50.746799] log file for today: File: '/home/akua/.local/share/io.ente.auth/logs/2026-6-12.txt' with prefix 
[ente_logging][INFO] [2026-06-12 23:25:50.746799] app version: '4.4.23+1023'
[ente_logging][INFO] [2026-06-12 23:25:50.746799] 
 [main][INFO] [2026-06-12 23:25:50.746927] Starting app in foreground

(io.ente.auth:14780): libayatana-appindicator-WARNING **: 23:25:50.749: libayatana-appindicator is deprecated. Please use libayatana-appindicator-glib in newly written code.
 [Configuration][INFO] [2026-06-12 23:25:50.870082] Skipping temp folder clear
 [Configuration][INFO] [2026-06-12 23:25:50.870219] User ID: 1580559962408878
 [AuthenticatorService][INFO] [2026-06-12 23:25:50.958390] Sync
 [AuthenticatorService][INFO] [2026-06-12 23:25:50.958448] Initiating remote to local sync
 [AuthenticatorService][INFO] [2026-06-12 23:25:50.958470] Current sync is xxx
 [HomePage][INFO] [2026-06-12 23:25:51.082953] No initial link received.
 [UpdateService][INFO] [2026-06-12 23:25:51.144752] Debouncing notification
 [AuthenticatorService][INFO] [2026-06-12 23:25:51.180006] 0 entries fetched from remote
 [AuthenticatorService][INFO] [2026-06-12 23:25:51.180070] remote fetch completed
 [AuthenticatorService][INFO] [2026-06-12 23:25:51.180101] Initiating local to remote sync
 [AuthenticatorService][INFO] [2026-06-12 23:25:51.181495] 0 entries to be updated at remote
 [AuthenticatorService][INFO] [2026-06-12 23:25:51.181522] local push completed
 [UpdateService][INFO] [2026-06-12 23:25:51.311410] Debouncing notification

```
