### ISSUE TITLE
[Auth] Allow simple .deb installation on Ubuntu 24.04 and later

### ISSUE THREAD

**Issue by wak-sudo** [ente-io/ente#3387]
### Description

Tested on the .deb file of  auth-v3.1.3

**Problem:**

On systems newer than Debian 10 .deb package can't be installed. 

Output from the ubuntu-24.04.1-desktop-amd64:

```
> sudo dpkg -i ente-auth-v3.1.3-x86_64.deb

Preparing to unpack ente-auth-v3.1.3-x86_64.deb ... 
Unpacking auth (3.1.3+323) ...
dpkg: dependency problems prevent configuration of auth: 
 auth depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.
 auth depends on gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1; however:
  Package gir1.2-appindicator3-0.1 is not installed.
  Package gir1.2-ayatanaappindicator3-0.1 is not installed.

dpkg: error processing package auth (--install): 
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ... 
Errors were encountered while processing:
 auth

> sudo apt install libwebkit2gtk-4.0-37

(...)
E: Package 'libwebkit2gtk-4.0-37' has no installation candidate.
```

Note: gir1.2-ayatanaappindicator3-0.1 is installable.

**Cause:**

libwebkit2gtk-4.0-37 is not present in Debian repos newer than Buster (10). In result, the same issue apply to many systems based on Debian, in particular Ubuntu newer than 19.

**Workaround:**

1. Edit /etc/apt/sources.list
2. Add "deb [trusted=yes] http://ftp.de.debian.org/debian buster main" (Germany based server, trusted can be omitted if repo is verified) 
3. sudo apt update
4. sudo dpkg -i ente-auth-v3.1.3-x86_64.deb (results in errors)
5. sudo apt install --fix-broken
6. sudo dpkg -i ente-auth-v3.1.3-x86_64.deb (installs fine)
7. Remove the added line from /etc/apt/sources.list

### Version

auth-v3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by Artim96** [comment]
Have you tried just using apt instead of dpkg? dpkg can't handle dependencies that aren't already installed. I'm on Testing and never had any issues with it, either through apt or gnome-software.

**Comment by wak-sudo** [comment]
`
> sudo apt install ./ente-auth-v3.1.3-x86_64.deb 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'auth' instead of './ente-auth-v3.1.3-x86_64.deb' 
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable 
distribution that some required packages have not yet been created or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 auth : Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.
`

Well, there's no difference between dpkg and apt if the underlying issue affects both.
From what I see, this problem has not been addressed at least since May 26 (#1870) and there are multiple entries for it (#2070, #2531,  #2987, #3106).  
Using AppImage is an alternative.

**Comment by Artim96** [comment]
> ```
> The following packages have unmet dependencies:
>  auth : Depends: libwebkit2gtk-4.0-37 but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```

To me this looks like an issue with Debian itself. Like I said, It does work flawlessly on Testing, though I might have been lucky. `libwebkit2gtk-4.0-37` currently is only available from stable and stable-backports. It has yet to reach Testing and the version in sid isn't available fro amd64 yet. But like I said, that is an issue Debian maintainers need to fix. What happens if you manually install `libwebkit2gtk-4.0-37`? Because usually apt tells you when it can't install a dependency because it in turn relies on something not available. But `libwebkit2gtk-4.0-37` clearly is available for any architecture supported, at least in Debian: [https://packages.debian.org/bookworm/libwebkit2gtk-4.0-37](https://packages.debian.org/bookworm/libwebkit2gtk-4.0-37). So your original comment about it missing on anything higher than Debian 10 is just plain false, as it's even available on Bullseye. And so is it at least in Ubuntu focal and all the way up to 23.10: https://packages.ubuntu.com/focal/libwebkit2gtk-4.0-37

So the only thing causing an issue is Ubuntu 24.04+ because they decided to drop support for `libwebkit2gtk-4.0-37`, while Debian won't scratch support before v13, and since it's still in sid it might survive at least until v14. So you might want to adapt your title to properly reflect on the actual situation. Because this issue has nothing to do with Debian and you don't experince it on Debian, but on Ubuntu. Debian 10 is now 5 years old and not even oldoldstable anymore, so you make the issue sound a lot more dramatic than it is. The issue looks more like the typical issues that will arise when you build your distro off of something that's literally named after a kid that's destroying all its toys.

**Comment by wak-sudo** [comment]
Artim96 is right. I must have made a series of mistakes while researching this issue. To my excuse I will say that I browsed Ubuntu and Debian repos, and checked the installation on Debian12, but came to wrong conclusions. I apologize for the introduced confusion. I will change the title to reflect the current state of the problem.

**Comment by shivam-effibuild** [comment]
I still see the issue in a fresh ubuntu install - 
Here is the `cat /etc/deviceinfo`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"


```bash
$ sudo dpkg -i ente-auth-v4.0.2-x86_64.deb 
Selecting previously unselected package auth.
(Reading database ... 178916 files and directories currently installed.)
Preparing to unpack ente-auth-v4.0.2-x86_64.deb ...
Unpacking auth (4.0.2+402) ...
dpkg: dependency problems prevent configuration of auth:
 auth depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.
 auth depends on gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1; however:
  Package gir1.2-appindicator3-0.1 is not installed.
  Package gir1.2-ayatanaappindicator3-0.1 is not installed.

dpkg: error processing package auth (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 auth

```

**Comment by shivam-effibuild** [comment]
The solution provided by @wak-sudo worked. Thanks.

**Comment by Artim96** [comment]
> I still see the issue in a fresh ubuntu install

Obviously you are. That's nothing Ubuntu will fix. Instead Ente would have to support libwebkit2gtk-4.1-x, and either drop support for libwebkit2gtk-4.0 or find a way to support both at the same time. As Debian dropped it in Testing and won't include it in Debian 13, Ubuntu has already dropped it too. Unless you run a distro based on something older than 24.04, the .deb package won't work. But since I have installed Ente Auth not that long ago on Testing, dropping that package is probably quite a recent thing, so it may take them a bit to figure out how to ideally have support for both current and future users, which would need support for both versions in parallel to not use people still on e.g. Debian 11 or Ubuntu 20.04, as they don't have libwebkit2gtk-4.1 available. And especially Ubuntu 20.04 is still getting updates.

**Comment by stancel** [comment]
> dy dropped it too. Unless you run a distro based on something older than 24.04, the .deb package won't work. But since I have installed Ente Auth not that l

This is correct. I have EnteAuth on versions of Ubuntu 24.04 that were upgraded and already had the needed libraries and then tried to install it on a fresh copy of Ubuntu 24.04 desktop. In order to get it to install properly, I had to go to Canonical's site and download the older versions of the library and install them first. That worked like a charm and I have been using it for months now on both the old/upgraded versions of Ubuntu 24.04 as well as the freshly installed version. Currently on version 4.2.3 that was released yesterday.

**Comment by Artim96** [comment]
> This has not been my experience with Linux Mint 22 and 22.1B. The .deb has installed on new bare metall installs from the installer (i.e. not an image) without problem.

Now it's not an issue anymore, but it was an issue. And the issue was that `libwebkit2gtk-4.0-37` isn't available anymore, it's too old. But in the mean time, that dependency has been removed.

**Comment by prateekmedia** [comment]
We have removed the dependency as also pointed out by @Eternal9100 and @Artim96 , let us know if this issue still exists and we'll reopen the issue.
